jwalton/node-amqp-connection-manager

src/ChannelWrapper.coffee, test/ChannelWrapperTest.coffee
@dule @calvinwiebe
This has two improvements.
First, this replaces `@_channelInProgress` with `@_settingUp`.  The idea behind `@_channelInProgress` was that when we got a new channel, we'd assign it to `@_channelInProgress`, run all the setup functions, then set it to `@_channel`.  This made it easy to figure out if a channel was fully set up or not.  Except, there were places where we were setting `@_channel` to null, where there might have been a `@_channelInProgress` that needed fixing.
Now, instead, we have `@_channel` which is created as soon as the channel is created, and `@_settingUp` which is either null (if we're all set up, or if there's no `@_channel`) or it's a promise that will resolve when all the setup functions have run.  This is a little easier to follow along with, I …
=> Better handling of closed channels, channels that are setting up.

src/AmqpConnectionManager.coffee
This should fix issue #8.  I tested by running "service rabbitmq-server restart" on the broker and witnessing connections reconnect after this patch was applied.
=> Fix issue #8 to reconnect when broker gracefully closes.

package.json
Lodash and promise breaker have fallen behind; this pr bumps them to latest.
[Breaking changes](https://github.com/jwalton/node-promise-breaker/blob/master/CHANGELOG.md) in promise-breaker centered around `pb.make`, a method which is not used in this codebase.
[Breaking changes](https://github.com/lodash/lodash/wiki/Changelog#v400) in lodash do not include any of the methods used in this repo: `_.without`, `_.isArray`, and `_.startsWith`
=> upgrade lodash to 4.15, promise-breaker to 3.0

README.md
I was reading through the docs and thought they might benefit from syntax highlighting.  This adds `js` tags around the examples in the README.  It does not change the actual content of the examples.
new rendering:
=> add js tag to readme code examples

src/AmqpConnectionManager.coffee, test/AmqpConnectionManagerTest.coffee, test/fixtures.coffee
(This is probably related to #14)
I found this issue that if RabbitMQ gracefully stopped, the sending queue will be halted indefinitely, even if the library successfully connected to other server. It seems that `AmqpConnectionManager` never fired `disconnect` event so the`ChannelWrapper` worker never stopped working and is still trying to send to the old channel.
Testing environment:
- RabbitMQ 3.6.10, Erlang 19.2.1 from `rabbitmq:management` image on Docker Hub
- Multiple instances of RabbitMQ running in a cluster
- Queue is a HA queue (ha-mode: all)
Steps to reproduce:
1. Produce a lot of messages and count the number of resolved publish promise (which is the number of messages sent)
2. On the node that the producer is connected to, run `rabbitmqctl stop_app`
3. Observe that the …
=> Fixed queued message never got sent after server gracefully closed connection

src/AmqpConnectionManager.coffee, test/AmqpConnectionManagerTest.coffee, test/fixtures.coffee
Events are fired when underlying amqplib detects RabbitMQ node is low on a resource (memory or disk)
* https://www.rabbitmq.com/connection-blocked.html
=> Fire blocked/unblocked events

README.md
=> docs: Fix a typo in the README file

src/AmqpConnectionManager.js, test/AmqpConnectionManagerTest.js
Adds support for passing a url object {url: string, connectionOptions?: object} as an alternative to a url string. Adds associated tests.
=> Support for per URL connection options

src/ChannelWrapper.js, test/ChannelWrapperTest.js
Before ChannelWrapper would always wait for a message to be confirmed before publishing the next message. This commit changes the behaviour so messages are published to the lower level channel as fast as they are received by the ChannelWrapper.
This means that for code like this, all messages will by published at once, instead of waiting for each message to be confirmed before publishing the next:
```js
await Promise.all(messages.map(message => channelWrapper.publish(message)))
```
=> Do not block while waiting for previous message to be confirmed

.gitignore, .vscode/settings.json, src/AmqpConnectionManager.js, src/ChannelWrapper.js
Allows for similar constructor call as amqplib:
```javascript
amqp.connect({
protocol: protocol,
hostname: host,
port: port,
username: username,
password: password
}).then(...);
```
=> Able to pass object as url

src/AmqpConnectionManager.js, src/helpers.js
When using this in a Jest test suite, there was an open handle detected. I looked into this and it seems that there is a hanging retry interval even after `.close()` has been called.
I have updated the helper `.wait()` method to be cancelable, meaning that this retry interval can be cancelled.
Heres the code coverage before:
```
=============================== Coverage summary ===============================
Statements   : 97.13% ( 203/209 )
Branches     : 91.94% ( 114/124 )
Functions    : 94.67% ( 71/75 )
Lines        : 97.45% ( 191/196 )
================================================================================
```
Heres the code coverage after:
```
=============================== Coverage summary ===============================
Statements   : 97.27% ( 214/220 )
Branches     : …
```
=> fix(package): resolve hanging retry connection timeout by introducing cancelable timeout

src/ChannelWrapper.js
This PR addresses issue #129. 
There didn't seem to be a good way to test it within the testing framework in the repository so I wrote a small repo script.
```js
var amqp = require('./lib/index');
async function main() {
var connection = amqp.connect(['amqp://guest:guest@localhost']);
var channelWrapper = connection.createChannel({
setup: function (channel) {
return channel.assertQueue('rxQueueName', { durable: true });
}
});
//this way works fine
console.log('starting serial queueing...')
for (let i = 0; i < 200000; i++) {
await channelWrapper.sendToQueue('rxQueueName', Buffer.from('serial'+i))
}
console.log(`finished serial queueing`)
//this way fails because is ignores drain
console.log('starting parallel queueing')
const promises = []
for (let i = 0; i < 200000; i++) { …
```
=> fix: issue with publish ignoring 'drain' event. 

src/AmqpConnectionManager.js
The AmqpConnectionManager close promise was resolved before the
underlying connection was fully closed.
=> fix: connection close not awaited

src/ChannelWrapper.js, test/ChannelWrapperTest.js
Fixes #95
The problem is that setup errors like 406 - Precondition failed causes the channel to close and thus no error to be emitted. Those errors will likely continue on each reconnect and ought to be emitted.
Can be tested against real Rabbitmq-server with
```javascript
const { once } = require('events');
let amqp = require('./lib/index');
async function main() {
let connection = amqp.connect(['amqp://guest:guest@localhost']);
await once(connection, 'connect');
console.log('connection connected!');
let channelWrapper = connection.createChannel({
setup: async function (channel) {
await channel.assertQueue('rxQueueName', { durable: true });
// When channel is closed, no errors will be emitted.
await channel.close();
// Uncomment the close line above to cause a 406 Precondition error …
```
=> fix: emit setup errors not caused by closed channel

src/AmqpConnectionManager.js
Since the error is that the connection failed to reconnect in socket timeout time, it is not necessary to wait any further before attempting to reconnect.
=> feat: immediately reconnect on amqplib connect timeout

src/ChannelWrapper.js
Hi!
I found a problem during the reconnection.
The messages are sent in the wrong order causing some inconsistency for example when using AMQP for RPC calls.
To better explain the problem see the following image:
This PR solves this problem but I'm not totally sure that the code is order-bulletproof (there may be some edge cases).
Another option would be to store data in an timestamp ordered array but can cause some overhead.
Let me know what you think!
=> preserve the publishing order on unexpected disconnection

src/ChannelWrapper.ts
With one of the latest releases - it seems like `teardown` was assigned to the wrong type (update: it always had this wrong type since the migration to TS).
On this line [ChannelWrapper.ts#L228](
https://github.com/jwalton/node-amqp-connection-manager/blob/master/src/ChannelWrapper.ts#L228) the channel is being passed, not the Error.
=> Fixing teardown type

package.json
`ts-node` and `typescript` should be listed in `devDependencies` instead of `dependencies` to prevent unnecessary installation for package users.
=> chore: move ts-node and typescript to devDeps

CHANGELOG.md, package.json, src/AmqpConnectionManager.ts, src/ChannelWrapper.ts, src/index.ts, test/AmqpConnectionManagerTest.ts, test/ChannelWrapperTest.ts, test/fixtures.ts, test/importTest.ts, test/integrationTest.ts
Exposes the underlying class and extracts the connect method
its constructor. The reason for this is that we might want to
initiate the connection later or await its result. With this code
change we can also more easily reject on operational errors and
set a timeout for the initial connect.
The naming is strange because I don't want to introduce any
breaking change.
Note that jest complains about leaking resources due to:
https://github.com/squaremo/amqp.node/pull/584
=> feat: expose AmqpConnectionManagerClass

README.md, src/ChannelWrapper.ts, src/index.ts, test/ChannelWrapperTest.ts, test/fixtures.ts, test/integrationTest.ts
Options to use channel without confirms
BREAKING CHANGE: the typescript signatures are changed when the
underlying channel either can be a Channel or ConfirmChannel
=> feat: plain channel

src/ChannelWrapper.ts, test/ChannelWrapperTest.ts, test/fixtures.ts
bindExchange, checkExchange, deleteExchange and unbindExchange were missing in ChannelWrapper.
=> feat: proxying every exchange function of amqplib

.github/workflows/github-ci.yaml, README.md, src/AmqpConnectionManager.ts, test/AmqpConnectionManagerTest.ts
Fixes #222.
This makes it so instead of emitting a `disconnect` event the first time we fail to connect, AmqpConnectionManager now emits a `connectFailed`.  AmqpConnectionManager emits `connectFailed` on every connection failure, and emits `disconnect` only when we transition from connected to disconnected.
BREAKING CHANGE: We will no longer emit a `disconnect` event on an
initial connection failure - instead we now emit `connectFailed` on each
connection failure, and only emit `disconnect` when we transition from
connected to disconnected.
=> fix: Emit `connectFailed` on connection failure.

src/AmqpConnectionManager.ts
`amqplib.credentials.external()` [does not contain](https://github.com/amqp-node/amqplib/blob/main/lib/credentials.js#L37-L42) a `username` or `password`, so a new accepted type has been added.
also mentioned in https://github.com/jwalton/node-amqp-connection-manager/issues/137#issuecomment-784494262
=> fix: accept type of amqplib.credentials.external()

src/ChannelWrapper.ts, test/ChannelWrapperTest.ts
=> feat: cancel specific consumer

src/AmqpConnectionManager.ts, test/AmqpConnectionManagerTest.ts
CloudAMQP recommend turning heartbeats off https://www.cloudamqp.com/docs/faq.html#closing-amqp-connection-error-heartbeattimeout.
amqplib also accept 0 for heartbeat parameter https://amqp-node.github.io/amqplib/channel_api.html#heartbeating
=> fix: accept 0 for heartbeatIntervalInSeconds

src/ChannelWrapper.ts, test/ChannelWrapperTest.ts
Fixes #297
If consume is called before the setup function is completed, the same consumer can be registered twice and cause a precondition error.
=> fix: consumer registered twice during setup

src/ChannelWrapper.ts, test/integrationTest.ts
=> fix: error thrown when queue deleted in amqplib 0.10.0

package.json, src/AmqpConnectionManager.ts
Related to https://github.com/jwalton/node-amqp-connection-manager/pull/303, it looks like now amqplib no longer has an `isOperational` flag on errors anymore.  It looks like this was a BlueBird thing, and amqplib switch to native promises so it was removed.
We used to fail immediately with a reject when trying to connect with a bad password, but because of the missing `isOperational` flag we don't anymore.  I fix this, and verified it on amqplib v0.8.0, then bumped the development version of amqplib to v0.10.3.
=> fix: Fail immediately for a bad password on latest amqplib.

src/index.ts
Fix that prevents Typescript from accidentally exposing `ChannelWrapper` as a class in emitted metadata(`emitDecoratorMetadata`).
Fixes #305, related to #249.
=> fix: exporting ChannelWrapper as a type without it getting emitted as metadata

src/ChannelWrapper.ts
Not sure if this was intentional or not, but exposing the interfaces makes it cleaner to implement a passthrough method like
`myConsumeMessagesMethod(consumptionFunction: Consumer["onMessage"], options?: ConsumerOptions):Promise<void>`
=> refactor: export Consumer and ConsumerOptions

package.json, tsconfig.json, tsconfig.types.json
When using `node16` or `nodenext` for `module` in `tsconfig.json` in combination with `commonjs` for `type` in `package.json`(which is also the default) Typescript will throw an error. This is because Typescript mark it as a ES module due to the closest `package.json` for the types being the one with `type` set to `module`. By exporting the types in a separate folder the issue is resolved.
Also it might be nice to introduce [`concurrently`](https://www.npmjs.com/package/concurrently) for the build process, so the compilation happens in parallel.
```json
"build": "concurrently  'tsc' 'tsc -p tsconfig.cjs.json' 'tsc -p tsconfig.types.json' && ./bin/build-types.sh",
```
=> fix: export types in separate directory
